parser: babel-eslint
parserOptions:
  ecmaFeatures: {jsx: true}
  ecmaVersion: 6
  sourceType: module
env:
  browser: true
  es6: true
  node: true
  jest/globals: true
extends:
  - airbnb
  - prettier
  - prettier/flowtype
  - prettier/react
  - plugin:jest/recommended
  - plugin:flowtype/recommended
  - plugin:testcafe/recommended
plugins:
  - import
  - react
  - jsx-a11y
  - json
  - jest
  - flowtype
  - prettier
  - testcafe
  - graphql
rules:
  global-require: warn
  no-underscore-dangle:
  - error
  - allow: [_id]
  import/extensions: [warn, {js: never}]
  import/no-extraneous-dependencies: off
  import/no-named-as-default: off
  jsx-a11y/no-noninteractive-element-interactions: off
  react/jsx-indent-props: [2, 2]
  react/require-default-props: off
  react/jsx-filename-extension:
  - warn
  - extensions: [.js, .jsx]
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/valid-expect: error
  prettier/prettier:
  - error
  - {
    singleQuote: true,
    trailingComma: all
  }
settings:
  import/resolver:
    node:
      moduleDirectory:
        - ./
        - ./client
        - ./node_modules
