sudo: required
language: node_js
services:
  - docker
node_js:
  - "node"
env:
  global:
    - CACHE_DIR=$HOME/.cache/docker
    - CACHE_DOCKER_IMAGE=$CACHE_DIR/build.tar.gz
before_install:
  - if [ -f ${CACHE_DOCKER_IMAGE} ]; then gunzip -c ${CACHE_DOCKER_IMAGE} | docker load; fi
  - docker build -t boilerplate:build --cache-from boilerplate:last .
  - docker tag boilerplate:build boilerplate:last
  - docker save boilerplate:last | gzip > ${CACHE_DOCKER_IMAGE}
  - yarn add greenkeeper-lockfile@1 -g
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn lint
  - yarn stylelint
  - yarn flow
  - yarn cover
after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
  - greenkeeper-lockfile-upload
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
  - node_modules
  - $CACHE_DIR
