sudo: required
language: node_js
services:
  - docker
node_js:
  - "node"
before_install:
  - docker build .
script:
  - yarn lint
  - yarn stylelint
  - yarn flow
  - yarn cover
after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
  - node_modules
